apiVersion: apps/v1
kind: Deployment
metadata:
  name: as-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: as
  template:
    metadata:
      labels:
        app: as
    spec:
      containers:
        - name: as
          image: yifud/authoritative-server:latest
          ports:
            - containerPort: 53533

---
apiVersion: v1
kind: Service
metadata:
  name: as-service
spec:
  selector:
    app: as
  ports:
    - protocol: TCP
      port: 53533
      targetPort: 53533
      nodePort: 30001
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fs-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fs
  template:
    metadata:
      labels:
        app: fs
    spec:
      containers:
        - name: fs
          image: yifud/fibonacci-server:latest
          ports:
            - containerPort: 9090
          env:
            - name: AS_SERVER_ADDRESS
              value: "http://as-service:53533"

---
apiVersion: v1
kind: Service
metadata:
  name: fs-service
spec:
  selector:
    app: fs
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30002
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: us-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: us
  template:
    metadata:
      labels:
        app: us
    spec:
      containers:
        - name: us
          image: yifud/user-server:latest
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: us-service
spec:
  selector:
    app: us
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30003
  type: NodePort
